### ISSUE TITLE
No root node in file and Not enough data conditions

### ISSUE THREAD

**Issue by nsankar** [uber-research/CRISP#1]
@chabbimilind  @assalmeftahi  Hi, I have a couple of queries.

1. Does the warning "No root node in file" impact the CP- Analysis ?
2. Even with more then 50+ json trace data files acquired from Jaeger for a specific service and operation defined for a Microservice, We got"not enough samples for P50 ,P95 and P99" . (the cctsAndtime list in process.py was found to be empty)  where as for another microservice 's service and operation , we could generate a CPA report with less than 10 trace data files (json). The question is (a) Under which circumstances, the not enough samples issue would occur ? (b) What is the min. size of samples?

Would greatly appreciate your response. Thanking you in advance

**Comment by chabbimilind** [comment]
@nsankar 
1. "No root node in file"  is just a warning and you can ignore it.
2. I have just pushed a patch, can you try on that one? It relaxes the requirement that the root span is the one that matches the service and operation name. In the failing case, were you feeding traces where the operation was not the root of the Jaeger trace? If this does not fix, please can you share your example traces and command you used?

**Comment by nsankar** [comment]
@chabbimilind 
Noted about #1
On #2 I will try the patch and revert. 

- Below is the trace data for the Service named --> frontend and operation --> Recv./product/1YMWWN1N4O
[1YMWWN1N4O.zip](https://github.com/uber-research/CRISP/files/7809657/1YMWWN1N4O.zip)

- I had used the command : 
- python3 process.py -a Recv./product/1YMWWN1N4O -s frontend -t my-trace-directory -o my-output dir

- The screenshot of this execution is as below
![image](https://user-images.githubusercontent.com/431890/148107074-33d0400b-c8bd-4c17-a6b5-c6689a6dee1e.png)


Thank you.

**Comment by chabbimilind** [comment]
I looked at `eb3a782e49ee083d57afb1bcbbe52a26.json`.
The `traceID` is `eb3a782e49ee083d57afb1bcbbe52a26`. 
There is no `spanID` that matches this `traceID`. 
Hence, we don't know the root of the graph.
How did you produce these traces? In my experience, a well-formed trace should have one spanID that is same as the traceID.

**Comment by vprithvi** [comment]
> In my experience, a well-formed trace should have one spanID that is same as the traceID.

This is an implementation detail - for e.g. the Jaeger Go Client sets the SpanID to the [lower 64 bits of the traceID](https://github.com/jaegertracing/jaeger-client-go/blob/master/tracer.go#L278). This assumption may not hold when using other means of creating spans, or even when creating spans with 128 bit traceIDs with the Jaeger client.

Identifying root spans by looking for spans with no [SpanReferences](https://opentracing.io/specification/#references-between-spans) would be a more robust alternative.

**Comment by chabbimilind** [comment]
Good point @vprithvi. I will relax the tool to not have this expectation.

**Comment by nsankar** [comment]
@chabbimilind  The trace data for CPA were collected using the Jaeger [HTTP JSON (Internal) mentioned here](https://www.jaegertracing.io/docs/1.29/apis/). While I am not a Jaeger expert, I believe  some of the trace  data in my working test app. does not seem to have well formed spandIDs which is the same as the TraceIDs per assumption . However, the [spanContext](https://opentracing.io/specification/#references-between-spans) is present. Hence I believe I get the warning / no data issues  for the various trace data i have been using for CPA analysis as reported herein. 

Pls. let me know once you have updated the tool to identify root spans by considering spans with "no SpanReferences" , I will test it for working under this condition and revert.  Thanks in advance.

**Comment by nsankar** [comment]
@chabbimilind I used the  updated CRISP code in the repo and tested it with the same data and get the same output as cited earlier
![image](https://user-images.githubusercontent.com/431890/148166761-667193f4-5910-48a3-a97c-43c0026f8f22.png)

**Comment by nsankar** [comment]
@chabbimilind , I included the two lines (253,254) shown in the screenshot below in graph.py _(from the latest updated repo here)_ which solved the  problem I had first reported here along with the sample data.

Just wanted to let you know. Hope  this is correct.  If this is something that can be broadly applied, you might want to include it and update the repo.

![image](https://user-images.githubusercontent.com/431890/149287644-0bf2eeba-f56b-42bd-bd34-c9bc59fa9b3c.png)

**Comment by chabbimilind** [comment]
@nsankar, thanks for the patch. I think the fix is reasonable. I was thinking of a more nuanced fix where:
1. We check for all spans that have zero references and make them all as "candidate" roots, and then
2. Within each rooted subtree search for the "service::operation" and stop on the first match 
3. Make the matching node as the rootNode (chop off its parent if any) and retain only that subtree for the rest of the processing. 
I haven't yet gotten to implementing it yet, if you happen to get there sooner, we will be happy to accept the patch.

PS: The reason for this elaborate fix is that when dealing with a large number of traces we have often come across traces with multiple roots. Your current solution will retain only the last root, and the service::operation may not be present in it or at the root of it.

**Comment by nsankar** [comment]
@chabbimilind  per your PS: comment, could you share a couple of Jaeger trace data sets with traces having multiple roots? That will help me in understanding the  trace structure you have mentioned and I can  try to expand  the patch / fix per your steps.

(On my side I won't get such complex traces data at this time..)
